volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 10

  kestra:
    restart: always
    image: kestra/kestra:latest
    env_file:
      - .env
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /home/kestra/creds.json:/.gcp/credentials.json
    environment:
      SECRET_GOOGLE_APPLICATION_CREDENTIALS: '/.gcp/credentials.json'
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@localhost.dev"
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
            scripts:
              docker:
                volume-enabled: true
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5432:5432"
    depends_on:
      postgres:
        condition: service_started