id: main
namespace: chi-traffic

inputs:
  - id: start_date
    type: DATETIME
    required: false
    displayName: "Start Date (optional)"

  - id: end_date
    type: DATETIME
    required: false
    displayName: "End Date (optional)"
    dependsOn:
      inputs:
        - start_date
      condition: "{{ inputs.start_date is not null }}"

tasks:

  - id: workingDirectory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/alepanti/ChiTrafficInsights
      branch: main

    - id: getAPIdata
      type: io.kestra.plugin.scripts.python.Commands
      taskRunner:
        type: io.kestra.plugin.core.runner.Process
      env:
        GCS_BUCKET_NAME: "{{ kv('GCS_BUCKET_NAME') }}"
        CSV_FILE_PATH: "{{ kv('CSV_FILE_PATH') }}"
      warningOnStdErr: false
      beforeCommands:
        - export START_DATE="{{ inputs.start_date | date('yyyy-MM-dd\'T\'HH:mm:ss.SSS') }}"
        - export END_DATE="{{ inputs.end_date | date('yyyy-MM-dd\'T\'HH:mm:ss.SSS') }}"
      commands:
        - python api_load/api_load.py
    
    - id: loadBQ
      type: io.kestra.plugin.scripts.python.Commands
      taskRunner:
        type: io.kestra.plugin.core.runner.Process
      env:
        SOURCES__FILESYSTEM__BUCKET_URL: "{{ kv('GCS_URL')}}"
        SOURCES__FILESYSTEM__FILE_GLOB: "*.csv"
      warningOnStdErr: false
      commands:
        - python dlt_bq/load_bq.py
      
    - id: dbtBuild
      type: io.kestra.plugin.dbt.cli.DbtCLI
      containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      inputFiles:
        sa.json: "{{kv('GCP_CREDS')}}"
      env:
        DBT_DATABASE: "{{kv('GCP_PROJECT_ID')}}"
        DBT_SCHEMA: "{{kv('GCP_DATASET')}}"
        DBT_RAW_DATASET: "{{ kv('DBT_RAW_DATASET') }}"
        GOOGLE_APPLICATION_CREDENTIALS: sa.json
      namespaceFiles:
        enabled: true
      storeManifest:
        key: manifest.json
        namespace: "{{ flow.namespace }}"
      projectDir: ./dbt
      commands:
        - dbt deps --project-dir ./dbt
        - dbt build --project-dir ./dbt

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    timezone: America/Chicago
    inputs:
      start_date: "{{ now() | dateAdd(-1, 'DAYS') | date('yyyy-MM-dd') }}T05:00:00Z"
      end_date: "{{ now() | date('yyyy-MM-dd') }}T05:00:00Z"