version: 2

models:
  - name: fct_traffic
    columns:
      - name: record_id
        data_type: STRING

      - name: date
        data_type: TIMESTAMP

      - name: speed
        data_type: NUMERIC

      - name: hour
        data_type: INT64

      - name: day_of_week
        data_type: INT64

      - name: weekday
        data_type: STRING

      - name: month
        data_type: INT64

      - name: year
        data_type: INT64

  - name: fct_avg_speed_by_region_hour
    columns:
      - name: date
        data_type: TIMESTAMP

      - name: region_id
        data_type: INT64

      - name: hour
        data_type: INT64
        
      - name: avg_speed
        data_type: NUMERIC

  - name: dim_region
    columns:
      - name: region_id
        data_type: INT64
      - name: region
        data_type: STRING

      - name: region_description
        data_type: STRING

  - name: dim_date
    columns:
      - name: date
        data_type: TIMESTAMP

      - name: hour
        data_type: INT64

      - name: day_of_week
        data_type: INT64

      - name: weekday
        data_type: STRING

      - name: month
        data_type: INT64

      - name: year
        data_type: INT64
