[destination.filesystem]
bucket_url = "gs://chi-traffic-json" # replace with your bucket name,

#[destination.credentials]
#project_id = "project_id" # please set me up!
#private_key = "private_key" # please set me up!
#client_email = "client_email" # please set me up!